---
- hosts: test
  user: gfs2
  tasks:
  - name: make direcotry
    file:
      path: ".ssh"
      state: directory
  - name: create empty file
    file:
      path: ".ssh/authorized_keys"
      state: touch
  - name: put pubkey
    lineinfile:
      path: ".ssh/authorized_keys"
      line: "Enter your ssh pub key"
